language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - ./BUILD.sh
  - pip install -U .
  - pip install -U git+https://github.com/kelceydamage/raspi-tasks.git@master
  - echo $(pwd)
before_script:
  - python3 /home/travis/build/kelceydamage/raspi-rtl/dummy.py
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - ls -l
  - mkdir -p /home/travis/var/run
  - cd /home/travis
script:
  - raspi-rtl start
  - ls -l
#  - python3 /home/travis/build/kelceydamage/raspi-rtl/platformTest.py
  - raspi-rtl stop
  - cd /home/travis/build/kelceydamage/raspi-rtl
  - pytest rtl/tests -v --cov=rtl.transport --cov-report=term-missing
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
after_success:
  - coveralls
  - codecov
env:
  global:
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - CODECLIMATE_REPO_TOKEN=[token]
    - CC_TEST_REPORTER_ID=[id]
