language: python
python:
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - py.test --doctest-modules -v --cov=rtl --cov-report=term-missing
after_success:
  - coveralls
  - codecov
